---
title: "R Notebook"
output: html_notebook
---

# Pronostico 2020-2025
```{r}
library(readxl)

test<- read_excel("E:/COSAS DE OSCAR DEFINITIVO/OSCAR/2020-2/Proyecto- PAPA/ANOMALIAS/ANOMALIAS POR CLUSTER/entrada pror departamento/cundinamarca/C0/tmed_cun_C0.xlsx", 
    sheet = "Hoja2")
test

test_PCP<- read_excel("E:/COSAS DE OSCAR DEFINITIVO/OSCAR/2020-2/Proyecto- PAPA/ANOMALIAS/ANOMALIAS POR CLUSTER/entrada pror departamento/cundinamarca/C0/PCP_cun_C0.xlsx", 
    sheet = "Hoja2")
test_PCP
library(tidyverse)
library(lubridate)
library(zoo)
library(ggfortify)
library(forecast)

tmed.ts=ts(test$prom,start = 1981,frequency = 12)
arima_tmed<-auto.arima(tmed.ts)
forecast_tmed<-forecast(arima_tmed,level = c(95), h = 60)
PCP.ts=ts(test_PCP$prom,start = 1981,frequency = 12)
arima_PCP<-auto.arima(PCP.ts)
forecast_PCP<-forecast(arima_PCP,level = c(95), h = 60)

pred_tmed_C1=autoplot(forecast_tmed)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Pronostico Temperatura media C1 - Cundinamarca",subtitle = "Periodo 1981-2025")

pred_PCP_C1=autoplot(forecast_PCP)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca",subtitle = "Periodo 1981-2025")

pred_tmed_C1
pred_PCP_C1

```


```{r}
año=c(2021:2025)
meses=c("año","enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre")
tmed_fut=matrix(forecast_tmed$mean)
tmed_fut=matrix(tmed_fut,12,5)
tmed_fut=data.frame(año,t(tmed_fut))
names(tmed_fut)=meses
tmed_fut
PCP_fut=matrix(forecast_PCP$mean)
PCP_fut=matrix(PCP_fut,12,5)
PCP_fut=data.frame(año,t(PCP_fut))
names(PCP_fut)=meses
PCP_fut

write.csv(tmed_fut,"tmed_fut_C1_cun.csv")
write.csv(PCP_fut,"PCP_fut_C1_cun.csv")
```

## series de tiempo

```{r}
tmed_1=ts(tmed_fut$enero,start = 2021,frequency = 1)
tmed_2=ts(tmed_fut$febrero,start = 2021,frequency = 1)
tmed_3=ts(tmed_fut$marzo,start = 2021,frequency = 1)
tmed_4=ts(tmed_fut$abril,start = 2021,frequency = 1)
tmed_5=ts(tmed_fut$mayo,start = 2021,frequency = 1)
tmed_6=ts(tmed_fut$junio,start = 2021,frequency = 1)
tmed_7=ts(tmed_fut$julio,start = 2021,frequency = 1)
tmed_8=ts(tmed_fut$agosto,start = 2021,frequency = 1)
tmed_9=ts(tmed_fut$septiembre,start = 2021,frequency = 1)
tmed_10=ts(tmed_fut$octubre,start = 2021,frequency = 1)
tmed_11=ts(tmed_fut$noviembre,start = 2021,frequency = 1)
tmed_12=ts(tmed_fut$diciembre,start = 2021,frequency = 1)

PCP_1=ts(PCP_fut$enero,start = 2021,frequency = 1)
PCP_2=ts(PCP_fut$febrero,start = 2021,frequency = 1)
PCP_3=ts(PCP_fut$marzo,start = 2021,frequency = 1)
PCP_4=ts(PCP_fut$abril,start = 2021,frequency = 1)
PCP_5=ts(PCP_fut$mayo,start = 2021,frequency = 1)
PCP_6=ts(PCP_fut$junio,start = 2021,frequency = 1)
PCP_7=ts(PCP_fut$julio,start = 2021,frequency = 1)
PCP_8=ts(PCP_fut$agosto,start = 2021,frequency = 1)
PCP_9=ts(PCP_fut$septiembre,start = 2021,frequency = 1)
PCP_10=ts(PCP_fut$octubre,start = 2021,frequency = 1)
PCP_11=ts(PCP_fut$noviembre,start = 2021,frequency = 1)
PCP_12=ts(PCP_fut$diciembre,start = 2021,frequency = 1)

```
## Graficos

```{r}
p_tmed_1=autoplot(tmed_1)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Enero",subtitle = "Periodo 2021-2025 Fase: Senescencia y Cosecha")+ geom_line(aes(y=tmed_1,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_2=autoplot(tmed_2)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Febrero",subtitle = "Periodo 2021-2025 Fase: Germinacion")+ geom_line(aes(y=tmed_2,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_3=autoplot(tmed_3)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Marzo",subtitle = "Periodo 2021-2025 Fase: Crec. Vegetativo, Ini. Tuberizacion y Llenado de tuberculo")+ geom_line(aes(y=tmed_3,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_4=autoplot(tmed_4)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Abril",subtitle = "Periodo 2021-2025 Fase: Llenado de tuberculo")+ geom_line(aes(y=tmed_4,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_5=autoplot(tmed_5)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Mayo",subtitle = "Periodo 2021-2025 Fase: Llenado de tuberculo y Senescencia")+ geom_line(aes(y=tmed_5,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_6=autoplot(tmed_6)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Junio",subtitle = "Periodo 2021-2025 Fase: Senescencia")+ geom_line(aes(y=tmed_6,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_7=autoplot(tmed_7)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Julio",subtitle = "Periodo 2021-2025 Fase: Senescencia y Cosecha")+ geom_line(aes(y=tmed_7,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_8=autoplot(tmed_8)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Agosto",subtitle = "Periodo 2021-2025 Fase: Germinacion")+ geom_line(aes(y=tmed_8,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_9=autoplot(tmed_9)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Septiembre",subtitle = "Periodo 2021-2025 Fase: Crec. Vegetativo, Ini. Tuberizacion y Llenado de tuberculo")+ geom_line(aes(y=tmed_9,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_10=autoplot(tmed_10)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Octubre",subtitle = "Periodo 2021-2025 Fase: Llenado de tuberculo")+ geom_line(aes(y=tmed_10,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_11=autoplot(tmed_11)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Noviembre",subtitle = "Periodo 2021-2025 Fase: Llenado de tuberculo y Senescencia")+ geom_line(aes(y=tmed_11,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))

p_tmed_12=autoplot(tmed_12)+xlab("Año")+ylab("Temperatura media [°C]")+ggtitle("Temperatura media C1 - Cundinamarca del mes: Diciembre",subtitle = "Periodo 2021-2025 Fase: Senescencia")+ geom_line(aes(y=tmed_12,colour="T. media °C"))  + geom_line(aes(y=10,colour="T. limite °C"))+ scale_colour_manual("", values=c("T. media °C"="black", "T. limite °C"="red"))



p_tmed_1
p_tmed_2
p_tmed_3
p_tmed_4
p_tmed_5
p_tmed_6
p_tmed_7
p_tmed_8
p_tmed_9
p_tmed_10
p_tmed_11
p_tmed_12

```
```{r}
p_PCP_1=autoplot(PCP_1)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Enero",subtitle = "Periodo 2021-2025 Fase: Senescencia y Cosecha")+ geom_line(aes(y=PCP_1,colour="PCP (mm)"))  + geom_line(aes(y=50,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_2=autoplot(PCP_2)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Febrero",subtitle = "Periodo 2021-2025 Fase: Germinacion")+ geom_line(aes(y=PCP_2,colour="PCP (mm)"))  + geom_line(aes(y=40,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_3=autoplot(PCP_3)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Marzo",subtitle = "Periodo 2021-2025 Fase: Crec. Vegetativo, Ini. Tuberizacion y Llenado de tuberculo")+ geom_line(aes(y=PCP_3,colour="PCP (mm)"))  + geom_line(aes(y=60,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_4=autoplot(PCP_4)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Abril",subtitle = "Periodo 2021-2025 Fase: Llenado de tuberculo")+ geom_line(aes(y=PCP_4,colour="PCP (mm)"))  + geom_line(aes(y=75,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_5=autoplot(PCP_5)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Mayo",subtitle = "Periodo 2021-2025 Fase: Llenado de tuberculo y Senescencia")+ geom_line(aes(y=PCP_5,colour="PCP (mm)"))  + geom_line(aes(y=75,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_6=autoplot(PCP_6)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Junio",subtitle = "Periodo 2021-2025 Fase: Senescencia")+ geom_line(aes(y=PCP_6,colour="PCP (mm)"))  + geom_line(aes(y=50,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_7=autoplot(PCP_7)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Julio",subtitle = "Periodo 2021-2025 Fase: Senescencia y Cosecha")+ geom_line(aes(y=PCP_7,colour="PCP (mm)"))  + geom_line(aes(y=50,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_8=autoplot(PCP_8)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Agosto",subtitle = "Periodo 2021-2025 Fase: Germinacion")+ geom_line(aes(y=PCP_8,colour="PCP (mm)"))  + geom_line(aes(y=40,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_9=autoplot(PCP_9)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Septiembre",subtitle = "Periodo 2021-2025 Fase: Crec. Vegetativo, Ini. Tuberizacion y Llenado de tuberculo")+ geom_line(aes(y=PCP_9,colour="PCP (mm)"))  + geom_line(aes(y=60,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_10=autoplot(PCP_10)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Octubre",subtitle = "Periodo 2021-2025 Fase: Llenado de tuberculo")+ geom_line(aes(y=PCP_10,colour="PCP (mm)"))  + geom_line(aes(y=75,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_11=autoplot(PCP_11)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Noviembre",subtitle = "Periodo 2021-2025 Fase: Llenado de tuberculo y Senescencia")+ geom_line(aes(y=PCP_11,colour="PCP (mm)"))  + geom_line(aes(y=75,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))

p_PCP_12=autoplot(PCP_12)+xlab("Año")+ylab("Precipitacion [mm]")+ggtitle("Precipitacion C1 - Cundinamarca del mes: Diciembre",subtitle = "Periodo 2021-2025 Fase: Senescencia")+ geom_line(aes(y=PCP_12,colour="PCP (mm)"))  + geom_line(aes(y=50,colour="Req. PCP (mm)"))+ scale_colour_manual("", values=c("PCP (mm)"="black", "Req. PCP (mm)"="red"))



p_PCP_1
p_PCP_2
p_PCP_3
p_PCP_4
p_PCP_5
p_PCP_6
p_PCP_7
p_PCP_8
p_PCP_9
p_PCP_10
p_PCP_11
p_PCP_12

```







